on:
  pull_request:

name: Regression tests

jobs:

  build_and_regression:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y && cargo install cargo-tarpaulin

    - name: build
      run: cargo build --release

    - name: setup
      run: mkdir ~/bin && PATH=$PATH:~/bin && cp target/release/locker ~/bin/

    - name: regression tests
      run: source tests/regressions.sh -e
                                  
