on:
  push:

name: Regression CI tests

jobs:

  build_and_regression:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:

    - uses: actions/checkout@v3

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y && cargo install cargo-tarpaulin

    - name: build
      run: cargo build --release

    - name: regression tests
      run: |
        mkdir ~/bin && export PATH=$PATH:~/bin && cp target/release/locker ~/bin/
        source tests/regressions.sh -e -c
                                  
