name: release

on:
  push:
    branches: [ "main" ]
    tags:     'v*'
    paths-ignore:
      - 'doc/**'
      - '.github/**'
  workflow_dispatch:


jobs:
  build_test_and_bundle:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: unit tests
      run: cargo test --all --release

    - name: bundle
      shell: bash
      run: |
          mkdir Locker
          cp target/release/locker locker-${{ matrix.os }}

    - name: compress-bundle-windows
      if: startsWith(matrix.os, 'windows')
      run: Compress-Archive -Path folder/* -Destination new.zip

    - name: compress-bundle-normal
      if: !startsWith(matrix.os, 'windows')
      run: zip Locker-${{ matrix.os }}.zip LICENSE locker-${{ matrix.os }}

    - name: upload bundle
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}
        path: Locker-${{ matrix.os }}.zip

  release:
    needs: [build_test_and_bundle]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-22.04
    
    steps:

      - name: get linux build
        uses: actions/download-artifact@v3
        with:
          name: ubuntu-latest

      - name: get windows build
        uses: actions/download-artifact@v3
        with:
          name: windows-latest

      - name: get macos build
        uses: actions/download-artifact@v3
        with:
          name: macos-latest

      - name: pack
        run: |
              mkdir linux windows macos
              ls
              unzip Locker-ubuntu-latest.zip
              mv LICENSE linux/
              mv locker-ubuntu-latest linux/locker
              zip -r linux-x86_64.zip linux/
              unzip Locker-windows-latest.zip
              mv LICENSE windows/
              mv locker-windows-latest windows/locker
              zip -r windows.zip windows/
              unzip Locker-macos-latest.zip
              mv LICENSE macos/
              mv locker-macos-latest macos/locker
              zip -r macOS.zip macos/
              

  #     https://github.com/softprops/action-gh-release
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: true
          name: "release-${{ github.ref_name }}"
          tag_name: ${{ github.ref }}
          files: |
            linux-x86_64.zip
            windows.zip
            macOS.zip
