on:
  pull_request:

name: Cross platform

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: unit tests
      run: cargo build --release && cargo test --all  

    - name: regression tests
      shell: bash
      run: |
        mkdir ~/bin && export PATH=$PATH:~/bin && cp target/release/locker ~/bin/
        ./tests/regressions.sh -e

  build_and_test_coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y && cargo install cargo-tarpaulin

    - name: unit tests with coverage
      run: cargo build --release && cargo tarpaulin --out json

    - name: regression tests
      run: |
        mkdir ~/bin && export PATH=$PATH:~/bin && cp target/release/locker ~/bin/
        source tests/regressions.sh -e -c

    - name: upload bundle
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: tarpaulin-report.json

                                  
