on:
  push:
    branches-ignore: 'main'

name: CI

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y

    - name: unit tests
      run: cargo test --all                                      
